### PR TITLE
Fix searchbar icon alignment

### LINKED ISSUE #24: Search icon is a bit off?
image
Notice how the search icon is a bit lower than it should be. Let me know what you think.
image
This is more of where I think the search icon should be

### PR DESCRIPTION
**Pull request by GoogleGenius**
Fix #24

### CODE REVIEW

**Comment by GoogleGenius** [comment]
image

**Review by Ascent817 — COMMENTED** [review]
Can you send a screenshot of the new icon?

**Comment by Ascent817** [comment]
Can you move it a little to the right? Maybe just 5 pixels?

**Comment by GoogleGenius** [comment]
I just realized I can edit your message lol 
image

Anyway, technically if you inspect it, it is technically even on both sides but because the handle of the magnifying glass is relatively thin it appears to our eyes that it's uneven. Do you think we should still change it?

**Comment by Ascent817** [comment]
Yeah, I think moving to the right a little bit will look better. It's that way on the old website and I think it looks a bit better.

**Comment by Ascent817** [comment]
Screenshot?

**Comment by GoogleGenius** [comment]
image

**Review by Ascent817 — APPROVED** [review]

**Pull request merged**
