### PR TITLE
Disable contact buttons upon request

### PR DESCRIPTION
**Pull request by GoogleGenius**

### CODE REVIEW

**Comment by GoogleGenius** [comment]
@Ascent817 review this now!!! lol

**Review by Ascent817 — CHANGES_REQUESTED** [review]
Uh...What is this supposed to do? The buttons on the contact modal aren't greyed out or anything after I click them

**Comment by GoogleGenius** [comment]
> Uh...What is this supposed to do? The buttons on the contact modal aren't greyed out or anything after I click them

Does it not work? https://www.w3schools.com/jsref/prop_pushbutton_disabled.asp

**Comment by GoogleGenius** [comment]
Ok happy now?

**Review by Ascent817 — APPROVED** [review]

**Pull request merged**
